## Demonstração - Pytorch

### Tensors

In [1]:
import torch
import numpy as np

#Inicialização diretamente com dados - tipo inferido automaticamente
data = [[1, 2],[3, 4]]

x_data = torch.tensor(data)
print(x_data)

#Inicialização de um NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(x_np)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [2]:
#Cria tensor com shape específico e com valores 1.
#Shape (2, 3)
ones_tensor = torch.ones(2,3)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [3]:
#Cria tensor com shape específico e com valores 0.
#Shape (3, 5)
zeros_tensor = torch.zeros(3,5)
zeros_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [4]:
#concatenação de tensors
torch.cat([ones_tensor, ones_tensor], dim=1)


tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [5]:
#multiplicação de tensors

ones_tensor * 2

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [6]:
# Cria tensor com shape específico e com valores aleaórios.

#Shape (10, 3)
x = torch.randn(10, 3)
print(x)

#Shape(10, 2)
y = torch.randn(10, 2)
print(y)


tensor([[ 1.7376, -0.4068, -1.1454],
        [ 0.5361, -0.5176, -0.2921],
        [-0.8778, -0.8851, -1.8359],
        [-1.8658,  1.3471,  0.6483],
        [-0.4447,  0.1962,  1.3213],
        [-0.7680, -0.5010, -0.0920],
        [ 1.7461,  1.6073,  0.9853],
        [-0.5830, -1.5411, -1.1189],
        [-1.0410, -0.3967,  0.8480],
        [-1.3790, -1.6335, -0.4019]])
tensor([[ 2.9016, -0.7788],
        [ 1.9697,  0.1696],
        [ 0.8471,  1.0909],
        [-1.5662, -0.9512],
        [ 1.9371,  1.7973],
        [ 0.1038, -1.8724],
        [ 0.6162, -0.1926],
        [ 1.5061,  0.7002],
        [-1.2307, -1.4096],
        [ 0.6461,  0.1299]])


In [7]:
#Atributos de um tensor

print(f"Shape do tensor: {x.shape}")
print(f"Datatype do tensor: {x.dtype}")
print(f"Dispositivo onde o tensor está armazenado: {x.device}")

Shape do tensor: torch.Size([10, 3])
Datatype do tensor: torch.float32
Dispositivo onde o tensor está armazenado: cpu


In [8]:
# Movendo o tensor para a GPU se disponível 
if torch.cuda.is_available():
    x = x.to('cuda')
    
print(f"Dispositivo onde o tensor está armazenado: {x.device}")

Dispositivo onde o tensor está armazenado: cuda:0


### Manipulação de tensor 

As operações são similares a um Np-array


In [9]:
print(x)
print()
print('Primeira linha: ', x[0,:])
print('Primeira coluna: ', x[:, 0])
print('Ultima coluna:', x[:, -1])


tensor([[ 1.7376, -0.4068, -1.1454],
        [ 0.5361, -0.5176, -0.2921],
        [-0.8778, -0.8851, -1.8359],
        [-1.8658,  1.3471,  0.6483],
        [-0.4447,  0.1962,  1.3213],
        [-0.7680, -0.5010, -0.0920],
        [ 1.7461,  1.6073,  0.9853],
        [-0.5830, -1.5411, -1.1189],
        [-1.0410, -0.3967,  0.8480],
        [-1.3790, -1.6335, -0.4019]], device='cuda:0')

Primeira linha:  tensor([ 1.7376, -0.4068, -1.1454], device='cuda:0')
Primeira coluna:  tensor([ 1.7376,  0.5361, -0.8778, -1.8658, -0.4447, -0.7680,  1.7461, -0.5830,
        -1.0410, -1.3790], device='cuda:0')
Ultima coluna: tensor([-1.1454, -0.2921, -1.8359,  0.6483,  1.3213, -0.0920,  0.9853, -1.1189,
         0.8480, -0.4019], device='cuda:0')


# Criando modelos

## Primeiro modelo

Aqui é apresentado um exemplo simples que utiliza uma camada completamente conectada.

Para acelerar as operações na rede neural, nós a movemos para a GPU, se disponível.

In [10]:
from torch import nn
import torch.nn.functional as F

# Construi uma camada fully connected
#torch.nn.Linear(in_features, out_features, bias=True, device=None, dtype=None)
linear = nn.Linear(3, 2)

print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[-0.1422, -0.4640, -0.4078],
        [ 0.1858, -0.5386, -0.3026]], requires_grad=True)
b:  Parameter containing:
tensor([ 0.0337, -0.5164], requires_grad=True)


In [11]:
# Pega a GPU ou CPU para treinamento.
device = "cuda" if torch.cuda.is_available() else "cpu"

print("Usando {}".format(device))

Usando cuda


In [12]:
linear = linear.to(device)

x = x.to(device)

#Operação - Forward.
pred = linear(x)
pred

#x, tensor criado acima, representa as features de entrada
#y, tensor criado acima, representa os valores alvo

tensor([[ 0.4426,  0.3723],
        [ 0.3168, -0.0496],
        [ 1.3179,  0.3528],
        [-0.5906, -1.7848],
        [-0.5330, -1.1045],
        [ 0.4128, -0.3614],
        [-1.3622, -1.3557],
        [ 1.2880,  0.5439],
        [ 0.0199, -0.7528],
        [ 1.1516,  0.2287]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [13]:
# Constroi a função de perda e otimização 
criterion = nn.MSELoss()

# Otimizador
optimizer = torch.optim.Adam(linear.parameters(), lr=0.001)


In [14]:
#Manda o y para a gpu
y = y.to(device)

# Computa a perda.
loss = criterion(pred, y)
print('Perda: ', loss.item())

# Propaga os erros (backpropagation) e atualiza os pesos
loss.backward()
optimizer.step() # 1-passo do 'gradient descent'

# Imprime a perda depois de 1 passo do gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('Perda depois de 1 passo de otimização : ', loss.item())

#Mais um passo - backpropagation e atualização de pesos
loss.backward()
optimizer.step()

# Imprime a perda depois de 2 passos do gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('Perda depois de 2 passos de otimização : ', loss.item())

Perda:  1.8532971143722534
Perda depois de 1 passo de otimização :  1.8499653339385986
Perda depois de 2 passos de otimização :  1.8467590808868408
