# Fatorização de Matriz

In [39]:
import data_processing
import pandas as pd
import numpy as np
import tensorflow as tf

data = data_processing.load_student_data()

In [51]:
def build_notas_sparse_tensor(df : pd.DataFrame):
  """
  Args:
    ratings_df: a pd.DataFrame with `user_id`, `movie_id` and `rating` columns.
  Returns:
    A tf.SparseTensor representing the ratings matrix.
  """
  # ========================= Complete this section ============================
  indices = df[['ID_ANONIMO', 'CODIGO']].values
  values = df['NOTA'].values
  # ============================================================================

  return tf.SparseTensor(
      indices=indices,
      values=values,
      dense_shape=[df['ID_ANONIMO'].shape[0], df['CODIGO'].shape[0]])

def id_to_index(df : pd.DataFrame):
    df2 = df.copy(deep = True)
    lista_ids = df['ID_ANONIMO'].unique()
    lista_codigos = df['CODIGO'].unique()
    df2['ID_ANONIMO'] = df['ID_ANONIMO'].astype('category').cat.codes
    df2['CODIGO'] = df['CODIGO'].astype('category').cat.codes

    return df2, lista_ids, lista_codigos

In [52]:
df_form, lista_ids, lista_codigos = id_to_index(data['formados'])

In [57]:
build_notas_sparse_tensor(df_form)

SparseTensor(indices=tf.Tensor(
[[  0 389]
 [  0 359]
 [  0 423]
 ...
 [295  78]
 [295 163]
 [295  97]], shape=(28889, 2), dtype=int64), values=tf.Tensor([ 8.2  7.   0.  ... -1.   9.4  9.8], shape=(28889,), dtype=float64), dense_shape=tf.Tensor([28889 28889], shape=(2,), dtype=int64))